version: '3'

services:
  token-redis:
    container_name: token-redis
    image: redis:latest
    networks:
      - auth
    ports:
      - "6379:6379"

  stateless-auth-db:
    container_name: stateless-auth-db
    image: postgres:12.5-alpine
    platform: linux/arm64
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    networks:
      - auth
    ports:
      - "5432:5432"

  stateful-auth-db:
    container_name: stateful-auth-db
    image: postgres:12.5-alpine
    platform: linux/arm64
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    networks:
      - auth
    ports:
      - "5433:5432"

  stateless-auth-api:
    build:
      context: './stateless-auth-api'
      platforms:
        - "linux/arm64"
    container_name: stateless-auth-api
    depends_on:
      - stateless-auth-db
    networks:
      - auth
    environment:
      - JWT_SECRET_KEY=c3RhdGVmdWwtc3RhdGVsZXNzLWF1dGhlbnRpY2F0aW9u
      - PORT=8080
      - DB_HOST=stateless-auth-db
      - DB_NAME=auth-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    ports:
      - 8080:8080

  stateless-any-api:
    build:
      context: './stateless-any-api'
      platforms:
        - "linux/arm64"
    container_name: stateless-any-api
    depends_on:
      - stateless-auth-db
    networks:
      - auth
    environment:
      - JWT_SECRET_KEY=c3RhdGVmdWwtc3RhdGVsZXNzLWF1dGhlbnRpY2F0aW9u
      - PORT=8081
    ports:
      - 8081:8081

  stateful-auth-api:
    build:
      context: './stateful-auth-api'
      platforms:
        - "linux/arm64"
    container_name: stateful-auth-api
    depends_on:
      - stateful-auth-db
    networks:
      - auth
    environment:
      - PORT=8082
      - DB_HOST=stateful-auth-db
      - DB_NAME=auth-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - REDIS_HOST=token-redis
      - REDIS_PORT=6379
    ports:
      - 8082:8082

  stateful-any-api:
    build:
      context: './stateful-any-api'
      platforms:
        - "linux/arm64"
    container_name: stateful-any-api
    depends_on:
      - stateful-auth-db
    networks:
      - auth
    environment:
      - PORT=8083
      - STATEFUL_AUTH_BASE_URL=http://stateful-auth-api:8082
    ports:
      - 8083:8083

networks:
  auth:
    driver: bridge
